site_name: Lesson learnt!
site_url: https://learn.omic.ch
repo_url: https://github.com/fabarea/lesson-learnt
#repo_name: "GitHub"
edit_uri: /fabarea/lesson-learnt/edit/master/public/
site_description:
site_author: "Fabien Udriot"
docs_dir: "public"
theme:
  name: "material"
